### ISSUE TITLE
Needed ability to hide field in independent way of  field type or rowMeta

### ISSUE THREAD

**Issue by DRITE** [tesler-platform/tesler-ui#230]

**Comment by Dergash** [comment]
This also means depreaction of [`hidden` field type](https://github.com/tesler-platform/tesler-ui/blob/ed5e3e6851955efb331a05e3ce65590df0c10861/src/interfaces/view.ts#L97) as it serve the same purpose but inferior in terms of not keeping original field type which blocks properly typed filtration of hidden fields
