### ISSUE TITLE
Required field check crash on autosave caused by drilldown.

### ISSUE THREAD

**Issue by ai-ba** [tesler-platform/tesler-ui#62]
Steps to reproduce:
1) Change value in table
2) Do save action on Form widget, that cause drilldown postaction

Drilldown postaction calls the autosave procedure for table data, which causes a required fields check.
Required fields check needs widget name to find widget data to work with. But it doesn't receive widget name, which leads to error caused by attempt to read empty object field.
Autosave action should provide widget name. It takes name of widget from action that caused autosave. But in our case, name of widget is not available in drilldown action.

**Comment by Dergash** [comment]
Merged
