### ISSUE TITLE
Hide elements in AssocListPopup hierarchy

### ISSUE THREAD

**Issue by AndrewRAM33** [tesler-platform/tesler-ui#691]
**extension request:**

Need to enable hiding items in `AssocListPopup` widgets with hierarchy. It is necessary in order to prevent the user from associating specific elements of the hierarchy.

**Comment by Dergash** [comment]
What kind of hiding you have in mind, id-based, like an array of ids to exclude in widget json?

Generally I'd say it makes more sense to exclude records by filtering them out in Tesler API service.

**Comment by AndrewRAM33** [comment]
Solved by a custom implementation of the multivalue field. Thanks
