### ISSUE TITLE
Filter and sort bugs

### ISSUE THREAD

**Issue by AndrewRAM33** [tesler-platform/tesler-ui#85]
The application has a problem in the operation of the filter and sorting when loading additional pages with data. There is also a problem with re-applying the filter.
**Conditions:**
_1. Set a filter, display a second page with data. The second page will be displayed without filtering.
2. Install the filter. Apply filter again the filter with the same value. All values ​​without a filter are displayed.
3. Set a filter by which there will be no data as a result. Apply filter again. The page will reload.
4. Set a filter, expand the entire list with data, apply sorting. Only the last page data is displayed._

**Comment by Dergash** [comment]
Merged https://github.com/tesler-platform/tesler-ui/pull/86
